language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
- 3.5
# Ref: https://travis-ci.community/t/pip-install-cryptography-fails-on-py36/11233/4
install: pip install -U tox-travis virtualenv
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: vVF7sibAQAaKdeEJw8j5RahM+iodCKyMqsa8EHc7T++FihmttNIEry3HxWzsP/4z70GdAMpnY8SuvLLiw18S8J40JsmGW8Rx3Zq0IDPUPWVYc4TTw1RCXgwP9LdieLDYzRrt7XIk/eqgPNQOsHUt4JfS/sOs5+r16pgcVOutOVTbToDKGyZrvz4eXkPo3fWzhyNpbHVTAXCzuFhMHEocseEVOxx4vWkpYGNUvSjNKmTA1V8nNjBZ6/e1RIrIM6tzYBoCOmZcM7SQIwg7wmTDuxrITqLfHDyCnA1MCNYMrIzQ36SSxhJBj8j1bpOhvdCCMYyPDruXSkacb3BwznbUPNiemujMJFlsdDyBIMj9y5xaDs7h7YVw4alLQ5z7FZ4aIAiJDKF+qjnVLC+MvtPRgfvzWjqskee1RxwgK2ZjKLcIjKMr4gL/ZVr1jftwikeEQ+ilOXRbp6p5gyx8JyDKnUVLHKFgFtkTwWpWuQNDN+qEa0RtXAb/oFquM1pX1p1paDbPIEAOsCabgJqB4jNc6szqE9cUQgrggUIXkBD1YQZs4JEvzrlraY9lEG+zeweFXkALs6p97CZpt3Js0m7EX0GIHuQrumRSIn6tvLKDb7LmqP8q+6OgNexGOyReeenG9AUTXX7wwlXLpxnXZ1qZlSl6cgZ8Yv6PubBtLF194hk=
  on:
    tags: true
    repo: rnag/wystia
    python: 3.8
